DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
                                     id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name     VARCHAR(300),
    email    VARCHAR(300) UNIQUE ,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items (
                                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name         VARCHAR(300),
    description  VARCHAR(1000),
    available    BOOLEAN NOT NULL,
    owner_id     BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL
    );

CREATE TABLE IF NOT EXISTS comments (
                                        id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text      VARCHAR(1000) NOT NULL,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL ,
    item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL ,
    created   TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS bookings (
                                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start_time TIMESTAMP,
                                        end_time   TIMESTAMP,
                                        item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL ,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL ,
    status     VARCHAR(300)
    );