DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
                                     id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name     VARCHAR(300),
                                     email    VARCHAR(300) UNIQUE ,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    description  VARCHAR(1000)                                  NOT NULL,
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
                                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name         VARCHAR(300),
                                     description  VARCHAR(1000),
                                     available    BOOLEAN NOT NULL,
                                     owner_id     BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
                                     request_id  BIGINT REFERENCES requests (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
                                        id        BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
                                        text      VARCHAR(1000)                                  NOT NULL,
                                        author_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
                                        item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
                                        created   TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
                                        CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start_time TIMESTAMP,
                                        end_time   TIMESTAMP,
                                        item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL ,
                                        booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL ,
                                        status     VARCHAR(300)
);